CREATE TABLE PREFIX_NAME(
	PREFIX_NAME_ID INT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
	PREFIX_NAME_TH VARCHAR(100) NOT NULL,
	PREFIX_NAME_EN VARCHAR(100) ,
	PRIMARY KEY (PREFIX_NAME_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO PREFIX_NAME VALUES
(1,'นาย','Mr')
,(2,'นาง','Mrs')
,(3,'นางสาว','Ms')
,(4,'อาจารย์',null);