CREATE TABLE MASTER_SECTION (
 	MASTER_SECTION_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
 	SECTION_YEAR INT(4) NOT NULL,
 	SECTION_SEMESTER  INT(1) NOT NULL,
 	FLAG TINYINT(1) NOT NULL,
 	STATUS INT(1) NOT NULL,
 	PRIMARY KEY (MASTER_SECTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO MASTER_SECTION VALUES(1,2555,1,1,0);
INSERT INTO MASTER_SECTION VALUES(2,2555,2,1,1);
INSERT INTO MASTER_SECTION VALUES(3,2555,3,1,0);
