CREATE TABLE SECTION (
 	SECTION_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
 	SECTION_NAME VARCHAR(10) NOT NULL,
 	COURSE_ID INT(10) UNSIGNED NOT NULL,
 	FLAG TINYINT(1) NOT NULL,
 	MASTER_SECTION_ID INT(10) UNSIGNED NOT NULL,
 	PRIMARY KEY (SECTION_ID),
 	FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID),
 	FOREIGN KEY (MASTER_SECTION_ID) REFERENCES MASTER_SECTION(MASTER_SECTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO SECTION VALUES(1,'011',1,1,1);
INSERT INTO SECTION VALUES(2,'021',1,1,1);
INSERT INTO SECTION VALUES(3,'011',1,1,2);
INSERT INTO SECTION VALUES(4,'021',1,1,2);