CREATE TABLE SECTION (
 	SECTION_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
 	SECTION_NAME VARCHAR(10) NOT NULL,
 	SECTION_YEAR INT(4) NOT NULL,
 	SECTION_SEMESTER INT(1) NOT NULL,
 	COURSE_ID INT(10) UNSIGNED NOT NULL,
 	FLAG TINYINT(1) NOT NULL,
 	PRIMARY KEY (SECTION_ID),
 	FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO SECTION VALUES(1,'011',2555,1,1,1);
INSERT INTO SECTION VALUES(2,'021',2555,1,1,1);
INSERT INTO SECTION VALUES(3,'011',2555,2,2,1);
INSERT INTO SECTION VALUES(4,'021',2555,2,2,1);
