CREATE TABLE USER_TYPE(
 TYPE INT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
 AUTHORITY VARCHAR(45) NOT NULL,
 TYPE_DESC VARCHAR(50),
 PRIMARY KEY(TYPE)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO USER_TYPE VALUES(1,'ROLE_ADMIN','ADMIN');
INSERT INTO USER_TYPE VALUES(2,'ROLE_TEACHER','TEACHER');
INSERT INTO USER_TYPE VALUES(3,'ROLE_STUDENT','STUDENT');