CREATE TABLE QUESTION(
 	QUESTION_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
 	QUESTION_TEXT TEXT NOT NULL,
 	QUESTION_GROUP_ID INT(10) UNSIGNED NOT NULL,
 	FLAG TINYINT(1) NOT NULL,
 	PRIMARY KEY(QUESTION_ID),
 	FOREIGN KEY (QUESTION_GROUP_ID) REFERENCES QUESTION_GROUP(QUESTION_GROUP_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;