CREATE TABLE ANSWER(
 ANSWER_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
 ANSWER_TEXT TEXT NOT NULL,
 ANSWER_SCORE INT(1) NOT NULL,
 QUESTION_ID INT(10) UNSIGNED NOT NULL,
 FLAG TINYINT(1) NOT NULL,
 PRIMARY KEY(ANSWER_ID),
 FOREIGN KEY(QUESTION_ID) REFERENCES QUESTION(QUESTION_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;