CREATE TABLE EXAM_QUESTION_GROUP(
	EXAM_QUESTION_GROUP_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	EXAM_ID INT(10) UNSIGNED NOT NULL,
	QUESTION_GROUP_ID INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (EXAM_QUESTION_GROUP_ID),
	UNIQUE (EXAM_ID,QUESTION_GROUP_ID),
 	FOREIGN KEY(EXAM_ID) REFERENCES EXAM(EXAM_ID),
 	FOREIGN KEY(QUESTION_GROUP_ID) REFERENCES QUESTION_GROUP(QUESTION_GROUP_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;