CREATE TABLE EXAM_RESULT_ANSWER(
	EXAM_RESULT_ANSWER_ID  INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	EXAM_RESULT_ID  INT(10) UNSIGNED NOT NULL,
	QUESTION_ID INT(10) UNSIGNED NOT NULL,
	ANSWER_ID INT(10) UNSIGNED,
	UNIQUE(EXAM_RESULT_ID,QUESTION_ID),
	PRIMARY KEY (EXAM_RESULT_ANSWER_ID),
	FOREIGN KEY (EXAM_RESULT_ID) REFERENCES EXAM_RESULT(EXAM_RESULT_ID),
	FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(QUESTION_ID),
	FOREIGN KEY (ANSWER_ID) REFERENCES ANSWER(ANSWER_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;