CREATE TABLE NEWS (
	NEWS_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	NEWS_HEADER VARCHAR(255) NOT NULL,
	NEWS_CONTENT TEXT NOT NULL,
	COURSE_ID INT(10) UNSIGNED,
	FLAG TINYINT(1) NOT NULL,
	UPDATE_DATE DATETIME NOT NULL,
	USERNAME VARCHAR(40) NOT NULL,
	PRIMARY KEY(NEWS_ID),
 	FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME),
	FOREIGN KEY(COURSE_ID) REFERENCES COURSE(COURSE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- COURSE ID > NULL = Web News