CREATE TABLE CONTENT_FILE (
	CONTENT_FILE_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	CONTENT_FILE_NAME VARCHAR(150) NOT NULL,
	CONTENT_FILE_PATH VARCHAR(255) NOT NULL,
	CONTENT_FILE_DESC VARCHAR(255),
	CONTENT_FILE_SIZE INT(10) UNSIGNED NOT NULL,
	CONTENT_PATH_ID INT(10) UNSIGNED NOT NULL,
	CREATE_DATETIME DATETIME NOT NULL,
	CREATE_BY VARCHAR(40) NOT NULL,
	PRIMARY KEY (CONTENT_FILE_ID),
	FOREIGN KEY (CONTENT_PATH_ID) REFERENCES CONTENT_PATH(CONTENT_PATH_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;