CREATE TABLE CONTENT_FILE (
	CONTENT_FILE_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	CONTENT_FILE_NAME VARCHAR(150) NOT NULL,
	CONTENT_FILE_PATH VARCHAR(255) NOT NULL,
	CONTENT_FILE_TYPE INT(2) UNSIGNED NOT NULL,
	CONTENT_FILE_DESC VARCHAR(255),
	CONTENT_FILE_SIZE INT(10) UNSIGNED NOT NULL,
	CONTENT_PATH_ID INT(10) UNSIGNED,
	CREATE_DATETIME DATETIME NOT NULL,
	CREATE_BY VARCHAR(40) NOT NULL,
	VIEW_COUNT INT(5) UNSIGNED NOT NULL,
	UNIQUE (CONTENT_FILE_NAME,CONTENT_PATH_ID),
	PRIMARY KEY (CONTENT_FILE_ID),
	FOREIGN KEY (CONTENT_PATH_ID) REFERENCES CONTENT_PATH(CONTENT_PATH_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- CONTENT_FILE_TYPE
-- 1 - Word
-- 2 - Excel
-- 3 - PowerPoint
-- 4 - PDF
-- 5 - Java
-- 6 - Zip
-- 7 - Other