CREATE TABLE CONTENT_PATH (
	CONTENT_PATH_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	CONTENT_PATH_NAME VARCHAR(150) NOT NULL,
	CONTENT_PATH_DESC VARCHAR(255),
	CONTENT_PATH_LOCATION VARCHAR(255),
	PARENT_PATH_ID INT(10) UNSIGNED,
	COURSE_ID INT(10) UNSIGNED,
	VIEW_COUNT INT(5) UNSIGNED NOT NULL,
	UNIQUE (CONTENT_PATH_NAME,PARENT_PATH_ID),
	PRIMARY KEY (CONTENT_PATH_ID),
	FOREIGN KEY (PARENT_PATH_ID) REFERENCES CONTENT_PATH(CONTENT_PATH_ID),
	FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO CONTENT_PATH VALUES (1,'ROOT',null,'resources',null,null,0);
INSERT INTO CONTENT_PATH VALUES (2,'CS.111',null,'resources/CS.111/',1,1,0);
INSERT INTO CONTENT_PATH VALUES (3,'CS.122',null,'resources/CS.122/',1,2,0);

