CREATE TABLE ASSIGNMENT_TASK (
	ASSIGNMENT_TASK_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	ASSIGNMENT_TASK_NAME VARCHAR(255) NOT NULL,
	ASSIGNMENT_DESC TEXT NOT NULL,
	START_DATE DATETIME NOT NULL,
	END_DATE DATETIME NOT NULL,
	NUM_OF_FILE INT(2) NOT NULL,
	LIMIT_FILE_SIZE_KB INT(10) UNSIGNED NOT NULL,
	COURSE_ID INT(10) UNSIGNED NOT NULL,
	CREATE_DATE DATETIME NOT NULL,
	CREATE_BY VARCHAR(40) NOT NULL,
	MAX_SCORE FLOAT(6) NOT NULL,
	FLAG TINYINT(1) NOT NULL,
	IS_EVALUATE_COMPLETE TINYINT(1) NOT NULL,
	PRIMARY KEY (ASSIGNMENT_TASK_ID),
	FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID),
	FOREIGN KEY (CREATE_BY) REFERENCES USERS(USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;