CREATE TABLE ASSIGNMENT_FILE (
	ASSIGNMENT_FILE_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	ASSIGNMENT_WORK_ID INT(10) UNSIGNED NOT NULL,
	CONTENT MEDIUMBLOB NOT NULL,
	FILE_NAME VARCHAR(255) NOT NULL,
	CONTENT_TYPE VARCHAR(255) NOT NULL,
	PRIMARY KEY (ASSIGNMENT_FILE_ID),
	FOREIGN KEY (ASSIGNMENT_WORK_ID) REFERENCES ASSIGNMENT_WORK(ASSIGNMENT_WORK_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;