CREATE TABLE PRE_EXAM_RESULT(
	PRE_EXAM_RESULT_ID  INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	PRE_EXAM_ID INT(10) UNSIGNED NOT NULL,
 	USERNAME VARCHAR(40) NOT NULL,
	NUM_OF_QUESTION INT NOT NULL,
	EXAM_COUNT INT NOT NULL,
	EXAM_START_DATE DATETIME NOT NULL,
	EXAM_EXPIRE_DATE DATETIME NOT NULL,
	EXAM_COMPLETE_DATE DATETIME,
	EXAM_COMPLETED TINYINT(1) NOT NULL,
	EXAM_IS_VIEWED TINYINT(1),
	EXAM_USED_TIME INT,
	EXAM_CORRECT INT
	PRIMARY KEY (PRE_EXAM_RESULT_ID),
	FOREIGN KEY (PRE_EXAM_ID) REFERENCES PRE_EXAM(PRE_EXAM_ID),
	FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;